### PR TITLE
fix: handle rpc conn loss in indexer

### LINKED ISSUE #21: Handle Connection Loss in Indexer Gracefully
**Description:**

The indexer task fails with the following error when the connection is lost to the Ethereum Sepolia endpoint:

```
2024-12-10T20:32:25.308676Z  WARN fossil_headers_db: Updater task failed: Failed to get latest block number

HTTP request error: reqwest::Error { kind: Request, url: "https://eth-sepolia.blastapi.io/e88cff07-b7b6-48d0-8be6-292f660dc735", source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Io, Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })) }
Caused by:
   0: error sending request for url (https://eth-sepolia.blastapi.io/e88cff07-b7b6-48d0-8be6-292f660dc735)
   1: client error (SendRequest)
   2: connection error
   3: Connection reset by peer (os error 104)

Location:
    src/rpc/mod.rs:87:26
```

---

**Expected Behavior:**
- The indexer should handle connection errors gracefully.
- Implement retry logic with exponential backoff for failed requests to the Ethereum RPC endpoint.
- Ensure that the indexer does not panic or terminate unexpectedly due to transient network issues.

---

**Priority:** High

---

**Proposed Solution:**
- Modify the RPC request logic in `src/rpc/mod.rs` to include retry logic for transient errors.
- Log retries and eventual failure after exceeding retry limits.
- Ensure the indexer can resume normal operations once the connection is restored.

---

**Additional Context:**
This issue impacts the reliability of the indexer and may lead to data gaps if the connection is intermittently lost. Proper handling of retries is critical to ensure consistent operation in production environments.

### PR DESCRIPTION
**Pull request by cwkang1998**
Handles the rpc connection loss in the indexer via adding a simple retry mechanism. Directly using the retry mechanisms already implemented for the db with some changes.

Closes #21

### CODE REVIEW

File: src/rpc/mod.rs [hunk 1]
```diff
@@ -112,3 +125,29 @@ async fn make_rpc_call<T: Serialize, R: for<'de> Deserialize<'de>>(
...
+    loop {
+        match make_rpc_call(params, timeout).await {
+            Ok(result) => return Ok(result),
+            Err(e) => {
+                attempts += 1;
+                if attempts > max_retries {
+                    warn!("Operation failed with error: {:?}. Max retries reached", e);
+                    return Err(e);
+                }
+                let backoff = Duration::from_secs(2_u64.pow(attempts));
```
Comment (ametel01) [inline src/rpc/mod.rs:144]: better if we avoid potential unbounded backoff duration by setting a max duration eg:

`let backoff = Duration::from_secs(2_u64.pow(attempts.min(10)));`

**Review by ametel01 — CHANGES_REQUESTED** [review]

File: src/rpc/mod.rs (hunk 1 above)
Comment (ametel01) [reply src/rpc/mod.rs:144]: Ready to merge once the above is addressed
